namespace Archean.Core.Models;

/// <summary>
/// The different types of blocks.
/// </summary>
public enum Block : byte
{
    Air = 0,
    Stone = 1,
    Grass = 2,
    Dirt = 3,
    Cobblestone = 4,
    Plank = 5,
    Sapling = 6,
    Bedrock = 7,
    FlowingWater = 8,
    Water = 9,
    FlowingLava = 10,
    Lava = 11,
    Sand = 12,
    Gravel = 13,
    GoldOre = 14,
    IronOre = 15,
    CoalOre = 16,
    Wood = 17,
    Leaves = 18,
    Sponge = 19,
    Glass = 20,
    RedCloth = 21,
    OrangeCloth = 22,
    YellowCloth = 23,
    LimeCloth = 24,
    GreenCloth = 25,
    TealCloth = 26,
    CyanCloth = 27,
    LightBlueCloth = 28,
    BlueCloth = 29,
    VioletCloth = 30,
    PurpleCloth = 31,
    MagentaCloth = 32,
    RoseCloth = 33,
    GrayCloth = 34,
    LightGrayCloth = 35,
    WhiteCloth = 36,
    YellowFlower = 37,
    RedFlower = 38,
    BrownMushroom = 39,
    RedMushroom = 40,
    GoldBlock = 41,
    IronBlock = 42,
    DoubleSlab = 43,
    Slab = 44,
    Brick = 45,
    Tnt = 46,
    Bookshelf = 47,
    MossyCobblestone = 48,
    Obsidian = 49
}
